"""Generate deployment config from the dialect files, the single source of truth.

Compose can't loop and nginx can't read JSON, so both derive their per-dialect
parts from app/dialects/<code>.json at COMMIT time (via the render-config
pre-commit hook), keeping the two in lockstep so they cannot drift. This script
writes two committed, reviewable artifacts:

  - compose.yml ............ one backend service per dialect, each with its own
                             mem_limit and baseline replicas from that dialect's
                             file, plus the proxy depends_on. Rendered from
                             compose.template.yml.
  - nginx/dialects.conf.template  routing map (/<dialect>/classify path segment
                             -> backend), the default backend, and the
                             invalid-dialect message. The proxy renders it to
                             /etc/nginx/conf.d/dialects.conf at startup via
                             nginx's built-in envsubst, filling ${DEFAULT_DIALECT}
                             (a runtime env) for docs routing.
  - .woodpecker/build-{latest,stable}-image.yaml  the per-dialect build steps and
                             the notify depends_on lists, rendered from the
                             hand-edited woodpecker-templates/{latest,stable}.yaml
                             (same template -> generated pattern as compose) so CI
                             builds every dialect's image with no hand edit. The
                             generated files carry a do-not-edit header; edit the
                             templates, where the check-lockfile gate and
                             everything else live.

Adding a dialect = drop app/dialects/<code>.json and commit; the hook
regenerates all of these. The dialect code is the filename stem; the backend
service is nuha-api-<code>:8000.

Run from the repo root:  python scripts/render_config.py
"""

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DIALECTS_DIR = ROOT / "app" / "dialects"

COMPOSE_TEMPLATE = ROOT / "compose.template.yml"
COMPOSE_OUTPUT = ROOT / "compose.yml"
NGINX_OUTPUT = ROOT / "nginx" / "dialects.conf.template"

DEPENDS_MARKER = "# __PROXY_DEPENDS_ON__  (generated)"
BACKENDS_MARKER = "# __BACKENDS__  (generated: one service per dialect)"

DEFAULT_MEM_LIMIT = "4g"
DEFAULT_REPLICAS = 1

GENERATED_HEADER = (
    "# GENERATED by scripts/render_config.py. Do not edit.\n"
    "# Edit compose.template.yml or add/remove app/dialects/<code>.json,\n"
    "# then re-run: python scripts/render_config.py\n"
)


def validate_dialect_config(code: str, cfg: dict) -> list[str]:
    """Return a list of structural problems with one dialect config (empty = OK).

    Pure and stdlib-only: no network, no import of the app or the ML stack, so it
    runs in the fast offline pre-commit hook. It mirrors what the app requires to
    boot and what the test suite asserts, so a structurally broken (but
    valid-JSON) dialect file is rejected at COMMIT time instead of only in CI.

    Out of scope on purpose (each stays where it belongs): whether
    ``preprocessing.type`` names a real preprocessor (that would couple this
    script to app.classifier's registry and break the "adding a preprocessor is a
    code-only change" rule -- the app checks it at import, the tests check it for
    every file), and whether ``hf_repo`` actually resolves on HuggingFace (the
    network model test and the Docker build cover that).
    """
    problems: list[str] = []

    def bad(msg: str) -> None:
        problems.append(f"{code}.json: {msg}")

    # The code (the file stem) is used verbatim as a Docker service name, an image
    # tag, and the nginx path segment (matched by ^/(?<dia>[a-z]+)/classify), so
    # constrain it to ASCII lowercase letters -- anything else breaks routing or
    # the compose/tag charset silently.
    if not (code.isascii() and code.islower() and code.isalpha()):
        bad("dialect code (the file stem) must be ASCII lowercase letters only (a-z)")

    missing = [
        f for f in ("name", "hf_repo", "languages", "preprocessing", "labels") if f not in cfg
    ]
    if missing:
        bad(f"missing required field(s): {', '.join(missing)}")
        return problems  # can't sensibly validate further without them

    if not (isinstance(cfg["name"], str) and cfg["name"].strip()):
        bad("'name' must be a non-empty string")

    repo = cfg["hf_repo"]
    if not (isinstance(repo, str) and repo.strip()):
        bad("'hf_repo' must be a non-empty string")
    elif (
        "://" in repo
        or any(c.isspace() for c in repo)
        or [p for p in repo.split("/") if p] != repo.split("/")
        or repo.count("/") != 1
    ):
        bad(f"'hf_repo' must be a 'namespace/name' id, got {repo!r}")

    langs = cfg["languages"]
    if not (isinstance(langs, dict) and langs):
        bad("'languages' must be a non-empty object")
        langs = {}
    for lc, meta in langs.items():
        if not (
            isinstance(meta, dict) and isinstance(meta.get("name"), str) and meta["name"].strip()
        ):
            bad(f"language '{lc}' needs a non-empty 'name'")
        aliases = meta.get("aliases", []) if isinstance(meta, dict) else None
        if aliases is not None and not (
            isinstance(aliases, list) and all(isinstance(a, str) and a.strip() for a in aliases)
        ):
            bad(f"language '{lc}' 'aliases' must be a list of non-empty strings")

    prep = cfg["preprocessing"]
    if not (isinstance(prep, dict) and isinstance(prep.get("type"), str) and prep["type"].strip()):
        bad("'preprocessing' must be an object with a non-empty 'type'")

    if "mem_limit" in cfg and not (
        isinstance(cfg["mem_limit"], str)
        and re.fullmatch(r"\d+(\.\d+)? ?[kmgtp]?i?b?", cfg["mem_limit"].strip(), re.IGNORECASE)
    ):
        bad("'mem_limit' must be a Docker memory size like '4g', '512m', or '1.5g'")
    if "replicas" in cfg and not (
        isinstance(cfg["replicas"], int)
        and not isinstance(cfg["replicas"], bool)
        and cfg["replicas"] >= 1
    ):
        bad("'replicas' must be an integer >= 1")

    problems.extend(_validate_labels(code, cfg["labels"], set(langs)))
    return problems


def _validate_labels(code: str, labels: object, declared_langs: set[str]) -> list[str]:
    """Validate the labels block: sub/main/sub_to_main present, label languages
    match the declared languages, digit keys, non-empty strings, consistent key
    sets across languages, and a sub_to_main that maps every sub id onto an
    existing main id (no orphans, no dangling targets)."""
    problems: list[str] = []

    def bad(msg: str) -> None:
        problems.append(f"{code}.json: {msg}")

    if not isinstance(labels, dict):
        bad("'labels' must be an object")
        return problems
    for key in ("sub", "main", "sub_to_main"):
        if not (isinstance(labels.get(key), dict) and labels[key]):
            bad(f"labels.{key} must be a non-empty object")
    if problems:
        return problems  # too broken to cross-check

    for cat in ("sub", "main"):
        if set(labels[cat]) != declared_langs:
            bad(
                f"labels.{cat} languages {sorted(labels[cat])} != "
                f"declared languages {sorted(declared_langs)}"
            )
        reference_keys = None
        for lc, mapping in labels[cat].items():
            if not (isinstance(mapping, dict) and mapping):
                bad(f"labels.{cat}.{lc} must be a non-empty object")
                continue
            for label_key, value in mapping.items():
                if not (isinstance(label_key, str) and label_key.isdigit()):
                    bad(f"labels.{cat}.{lc} key {label_key!r} must be a digit string")
                if not (isinstance(value, str) and value.strip()):
                    bad(f"labels.{cat}.{lc}[{label_key}] must be a non-empty string")
            if reference_keys is None:
                reference_keys = set(mapping)
            elif set(mapping) != reference_keys:
                bad(f"labels.{cat}.{lc} keys differ from the other languages")

    s2m = labels["sub_to_main"]
    sub_ids = {int(k) for k in next(iter(labels["sub"].values())) if str(k).isdigit()}
    main_ids = {int(k) for k in next(iter(labels["main"].values())) if str(k).isdigit()}
    for key, target in s2m.items():
        if not (isinstance(key, str) and key.isdigit()):
            bad(f"sub_to_main key {key!r} must be a digit string")
        if isinstance(target, bool) or not isinstance(target, int):
            bad(f"sub_to_main[{key}] must be an integer main id")
        elif target not in main_ids:
            bad(f"sub_to_main[{key}] -> {target} has no matching main label")
    mapped = {int(k) for k in s2m if str(k).isdigit()}
    if sub_ids - mapped:
        bad(f"sub ids {sorted(sub_ids - mapped)} have no sub_to_main mapping")
    if mapped - sub_ids:
        bad(f"sub_to_main has keys {sorted(mapped - sub_ids)} not present in sub labels")
    return problems


def load_dialects() -> dict[str, dict]:
    """Return {code: config} for every app/dialects/<code>.json, sorted by code.

    Fails loudly (SystemExit -> the render-config pre-commit hook rejects the
    commit) on a file that is invalid JSON or structurally broken, so a bad
    dialect file never reaches the generated config or CI.
    """
    dialects: dict[str, dict] = {}
    parse_errors: list[str] = []
    for path in sorted(DIALECTS_DIR.glob("*.json")):
        try:
            dialects[path.stem] = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            parse_errors.append(f"{path.name}: invalid JSON: {e}")
    if parse_errors:
        raise SystemExit("Broken dialect file(s):\n  " + "\n  ".join(parse_errors))
    if not dialects:
        raise SystemExit(f"No dialect files found in {DIALECTS_DIR}")

    problems = [p for code, cfg in dialects.items() for p in validate_dialect_config(code, cfg)]
    if problems:
        raise SystemExit(
            "Structurally invalid dialect file(s) — fix these before committing:\n  "
            + "\n  ".join(problems)
        )
    return dialects


def _default_dialect(codes: list[str]) -> str:
    """The dialect whose backend the proxy routes the docs pages to.

    Prefer 'arz' (the historical default) when it exists, else the first dialect
    code alphabetically. Derived from the dialect files, not hardcoded, so it
    stays valid even if 'arz' is removed or was never present -- an operator can
    still override it at runtime via the DEFAULT_DIALECT env.
    """
    return "arz" if "arz" in codes else sorted(codes)[0]


def render_compose(dialects: dict[str, dict]) -> str:
    codes = list(dialects)

    depends_on = "\n".join(
        f"      nuha-api-{code}:\n        condition: service_healthy" for code in codes
    )

    backends = []
    for code, cfg in dialects.items():
        # Per-dialect knobs come from the dialect file (the single source of truth
        # for anything dialect-specific): mem_limit and the baseline replica count.
        mem = cfg.get("mem_limit", DEFAULT_MEM_LIMIT)
        replicas = cfg.get("replicas", DEFAULT_REPLICAS)
        # No container_name: a service with replicas needs unique container names,
        # so Compose names them nuha-api-<code>-1, -2, ... The service name
        # nuha-api-<code> still resolves (via Docker DNS) to every replica, which
        # is what the proxy's variable proxy_pass and the depends_on use. To change
        # the baseline, edit "replicas" in the dialect file and re-render; for an
        # ad-hoc burst, `docker compose up --scale nuha-api-<code>=N`. cpu and the
        # memory reservation are uniform across dialects, so they stay shared env.
        # Each backend builds AND runs its own per-dialect image (only that
        # dialect's model is baked in). The image ref is
        # ${NUHA_IMAGE_PREFIX}:${NUHA_IMAGE_TAG_PREFIX}<code>: with both unset,
        # `docker compose build` yields the local nuha-api:<code> images and
        # `docker compose up` runs them. To run CI-published images, set
        # NUHA_IMAGE_PREFIX to the registry repo AND NUHA_IMAGE_TAG_PREFIX to a
        # channel ("stable-" or "latest-"), giving e.g. .../nuha-api:stable-acm.
        # The channel is a tag PREFIX because CI publishes channel-first tags
        # (stable-<code>); there is no bare <code> tag. The build passes
        # --build-arg DIALECT=<code>, which the Dockerfile uses to download only
        # that model; the runtime DIALECT env (below) must match the baked model.
        # image/build/DIALECT are per-dialect, so they are rendered here rather
        # than shared via the x-backend anchor.
        backends.append(
            f"  nuha-api-{code}:\n"
            f"    <<: *backend\n"
            f"    image: ${{NUHA_IMAGE_PREFIX:-nuha-api}}:${{NUHA_IMAGE_TAG_PREFIX:-}}{code}\n"
            f"    build:\n"
            f"      context: .\n"
            f"      dockerfile: Dockerfile\n"
            f"      args:\n"
            f"        - DIALECT={code}\n"
            f"    environment:\n"
            f"      - DIALECT={code}\n"
            f"    deploy:\n"
            f"      replicas: {replicas}\n"
            f"      resources:\n"
            f"        limits:\n"
            f'          cpus: "${{BACKEND_CPU_LIMIT:-2.0}}"\n'
            f"          memory: {mem}\n"
            f"        reservations:\n"
            f"          memory: ${{BACKEND_MEM_RESERVATION:-512m}}"
        )

    text = COMPOSE_TEMPLATE.read_text(encoding="utf-8")
    # Drop the template's own leading comment block (the same robust helper
    # render_woodpecker uses, rather than keying on a sentinel word in the comment).
    text = _strip_leading_comment(text)
    text = text.replace(DEPENDS_MARKER, depends_on)
    text = text.replace(BACKENDS_MARKER, "\n\n".join(backends))
    # Fill the proxy's DEFAULT_DIALECT fallback from the dialect files rather than
    # leaving a hardcoded 'arz' that would dangle if arz is absent. The template
    # carries the 'arz' literal as the source default; substitute the computed
    # one (a no-op when arz is present, so the committed file is unchanged then).
    placeholder = "${DEFAULT_DIALECT:-arz}"
    if placeholder not in text:
        raise SystemExit(
            f"compose.template.yml is missing the {placeholder!r} placeholder that "
            "render_compose rewrites with the derived default dialect (fail loudly "
            "rather than emit a compose.yml whose proxy default silently dangles)"
        )
    text = text.replace(placeholder, f"${{DEFAULT_DIALECT:-{_default_dialect(codes)}}}")
    return GENERATED_HEADER + text


def render_nginx(dialects: dict[str, dict]) -> str:
    codes = list(dialects)
    human_list = ", ".join(codes)

    lines = [
        "# GENERATED by scripts/render_config.py. Do not edit.",
        "# Edit app/dialects/<code>.json and re-render, not this file.",
        "# Rendered to /etc/nginx/conf.d/dialects.conf at container start; nginx",
        "# envsubst fills the default-dialect placeholder below (NGINX_ENVSUBST_FILTER",
        "# limits substitution to that one variable, leaving nginx $vars intact).",
        "# Maps the dialect PATH segment (the <dialect> in /<dialect>/classify",
        "# [/batch]) captured by the proxy as $dia to the matching backend. No",
        "# empty-key fallback: the path form always names a dialect, so an unknown",
        "# one -> '' -> 400 (the location returns 460 -> @invalid_dialect).",
        "map $dia $path_backend {",
    ]
    for code in codes:
        lines.append(f"    {code:<7} nuha-api-{code}:8000;")
    lines += [
        '    default "";',
        "}",
        "# The default backend serves the dialect-independent docs. It is a",
        "# constant, but written as a map so proxy_pass stays a $variable -> per-",
        "# request Docker DNS resolution and replica round-robin, like the path",
        "# backends above.",
        "map $host $default_backend { default nuha-api-${DEFAULT_DIALECT}:8000; }",
        f'map $host $invalid_dialect_msg {{ default "Invalid dialect. '
        f'Must be one of: {human_list}."; }}',
        "",
    ]
    return "\n".join(lines)


# --- Woodpecker CI -----------------------------------------------------------
# The two pipeline files build one image per dialect. Each is rendered from a
# hand-edited woodpecker-templates/<channel>.yaml (the same template -> generated
# pattern as compose.template.yml -> compose.yml): render_config fills the build
# steps and the notify depends_on lists, one entry per dialect, so adding a
# dialect needs no CI edit. The templates live in woodpecker-templates/, not in
# .woodpecker/, because any *.yaml under .woodpecker/ is parsed as a pipeline.
# Everything else (triggers, secrets, notify steps, the single check-lockfile
# gate) is hand-edited in the template.
WOODPECKER_FILES = {
    "latest": {
        "template": ROOT / "woodpecker-templates" / "latest.yaml",
        "output": ROOT / ".woodpecker" / "build-latest-image.yaml",
    },
    "stable": {
        "template": ROOT / "woodpecker-templates" / "stable.yaml",
        "output": ROOT / ".woodpecker" / "build-stable-image.yaml",
    },
}

# Marker tokens the templates carry on their own lines; render fills each with one
# entry per dialect. Matched by substring, not exact text, so the human-readable
# annotation after the token can be edited freely without breaking the render.
BUILD_STEPS_TOKEN = "__BUILD_STEPS__"
BUILD_DEPENDS_TOKEN = "__BUILD_DEPENDS__"


def _wp_build_step(channel: str, code: str) -> str:
    """One docker-buildx build step for a dialect on the latest or stable channel.

    Published tags are <channel>-<dialect> and, for rollback, the checksum-pinned
    <channel>-<CI_COMMIT_SHA>-<dialect> (e.g. stable-acm, stable-<sha>-acm,
    latest-acm, latest-<sha>-acm). Channel-first so all of a channel's tags sort
    together in the registry; no bare <dialect> tag, so every published image
    states its channel and a branch build can't overwrite what a deploy pulls.
    """
    tags = (f"{channel}-{code}", f"{channel}-${{CI_COMMIT_SHA}}-{code}")
    tag_lines = "\n".join(f"        - {t}" for t in tags)
    # build_args MUST be a map: given a list the plugin collapses it into a
    # single "*" arg, so the build args (DIALECT included) never get set.
    return (
        f"  - name: build-{channel}-image-{code}\n"
        f"    image: woodpeckerci/plugin-docker-buildx:6.1.0\n"
        f"    settings:\n"
        f"      repo: *docker_repo\n"
        f"      registry: *registry_url\n"
        f"      dockerfile: ./Dockerfile\n"
        f"      tags:\n"
        f"{tag_lines}\n"
        f"      username:\n"
        f"        from_secret: REGISTRY_USERNAME\n"
        f"      password:\n"
        f"        from_secret: REGISTRY_SECRET\n"
        f"      build_args:\n"
        f"        DIALECT: {code}\n"
        f"        CI_COMMIT_SHA: ${{CI_COMMIT_SHA}}\n"
        f"        CI_REPO_URL: ${{CI_REPO_URL}}\n"
        f"        CI_PIPELINE_CREATED: ${{CI_PIPELINE_CREATED}}\n"
        f"    depends_on:\n"
        f"      - run-pre-commit-hooks\n"
        f"      - check-lockfile\n"
        f"      - run-tests"
    )


def _woodpecker_header(template_name: str) -> str:
    return (
        "# GENERATED by scripts/render_config.py. Do not edit.\n"
        f"# Edit {template_name} or add/remove app/dialects/<code>.json,\n"
        "# then re-run: python scripts/render_config.py\n"
    )


def _strip_leading_comment(text: str) -> str:
    """Drop the template's leading comment block (the opening run of blank and #
    lines) so the generated file starts at the first real key. Robust to whatever
    the comment says, unlike keying on a sentinel word in it."""
    lines = text.split("\n")
    i = 0
    while i < len(lines) and (not lines[i].strip() or lines[i].lstrip().startswith("#")):
        i += 1
    return "\n".join(lines[i:])


def _fill_marker(text: str, token: str, block: str, where: str) -> str:
    """Replace every line containing `token` with `block`. Raises if the token is
    absent, so a template that lost its marker fails the render (and the pre-commit
    hook) loudly instead of silently dropping a generated section."""
    lines = text.split("\n")
    if not any(token in ln for ln in lines):
        raise SystemExit(f"render_config: marker {token} not found in {where}")
    return "\n".join(block if token in ln else ln for ln in lines)


def render_woodpecker(dialects: dict[str, dict]) -> None:
    """Render each .woodpecker pipeline from its hand-edited template.

    Fills the build-steps and notify-depends markers with one entry per dialect,
    drops the template's own leading comment, and stamps a do-not-edit header on
    the generated file (mirrors render_compose)."""
    codes = list(dialects)
    for channel, paths in WOODPECKER_FILES.items():
        steps = "\n\n".join(_wp_build_step(channel, c) for c in codes)
        depends = "\n".join(f"      - build-{channel}-image-{c}" for c in codes)
        ref = paths["template"].relative_to(ROOT).as_posix()
        text = _strip_leading_comment(paths["template"].read_text(encoding="utf-8"))
        text = _fill_marker(text, BUILD_STEPS_TOKEN, steps, ref)
        text = _fill_marker(text, BUILD_DEPENDS_TOKEN, depends, ref)
        paths["output"].write_text(_woodpecker_header(ref) + text, encoding="utf-8")


def main() -> None:
    dialects = load_dialects()

    COMPOSE_OUTPUT.write_text(render_compose(dialects), encoding="utf-8")
    NGINX_OUTPUT.parent.mkdir(exist_ok=True)
    NGINX_OUTPUT.write_text(render_nginx(dialects), encoding="utf-8")
    render_woodpecker(dialects)

    codes = ", ".join(dialects)
    print(
        f"wrote compose.yml, nginx/dialects.conf.template, and the .woodpecker "
        f"build steps for dialects: {codes}"
    )


if __name__ == "__main__":
    main()
