"""Generate deployment config from the dialect files, the single source of truth.

Compose can't loop and nginx can't read JSON, so both derive their per-dialect
parts from app/dialects/<code>.json at COMMIT time (via the render-config
pre-commit hook), keeping the two in lockstep so they cannot drift. This script
writes two committed, reviewable artifacts:

  - compose.yml ............ one backend service per dialect, each with its own
                             mem_limit and baseline replicas from that dialect's
                             file, plus the proxy depends_on. Rendered from
                             compose.template.yml.
  - nginx/dialects.conf.template  routing map (?dialect= -> backend), docs
                             backend, and the invalid-dialect message. The proxy
                             renders it to /etc/nginx/conf.d/dialects.conf at
                             startup via nginx's built-in envsubst, filling
                             ${DEFAULT_DIALECT} (a runtime env) for the
                             no-dialect fallback and docs routing.

Adding a dialect = drop app/dialects/<code>.json and commit; the hook
regenerates both. The dialect code is the filename stem; the backend service is
nuha-api-<code>:8000.

Run from the repo root:  python scripts/render_config.py
"""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DIALECTS_DIR = ROOT / "app" / "dialects"

COMPOSE_TEMPLATE = ROOT / "compose.template.yml"
COMPOSE_OUTPUT = ROOT / "compose.yml"
NGINX_OUTPUT = ROOT / "nginx" / "dialects.conf.template"

DEPENDS_MARKER = "# __PROXY_DEPENDS_ON__  (generated)"
BACKENDS_MARKER = "# __BACKENDS__  (generated: one service per dialect)"

DEFAULT_MEM_LIMIT = "4g"
DEFAULT_REPLICAS = 1

GENERATED_HEADER = (
    "# GENERATED by scripts/render_config.py. Do not edit.\n"
    "# Edit compose.template.yml or add/remove app/dialects/<code>.json,\n"
    "# then re-run: python scripts/render_config.py\n"
)


def load_dialects() -> dict[str, dict]:
    """Return {code: config} for every app/dialects/<code>.json, sorted by code."""
    dialects = {
        p.stem: json.loads(p.read_text(encoding="utf-8"))
        for p in sorted(DIALECTS_DIR.glob("*.json"))
    }
    if not dialects:
        raise SystemExit(f"No dialect files found in {DIALECTS_DIR}")
    return dialects


def render_compose(dialects: dict[str, dict]) -> str:
    codes = list(dialects)

    depends_on = "\n".join(
        f"      nuha-api-{code}:\n        condition: service_healthy" for code in codes
    )

    backends = []
    for code, cfg in dialects.items():
        # Per-dialect knobs come from the dialect file (the single source of truth
        # for anything dialect-specific): mem_limit and the baseline replica count.
        mem = cfg.get("mem_limit", DEFAULT_MEM_LIMIT)
        replicas = cfg.get("replicas", DEFAULT_REPLICAS)
        # No container_name: a service with replicas needs unique container names,
        # so Compose names them nuha-api-<code>-1, -2, ... The service name
        # nuha-api-<code> still resolves (via Docker DNS) to every replica, which
        # is what the proxy's variable proxy_pass and the depends_on use. To change
        # the baseline, edit "replicas" in the dialect file and re-render; for an
        # ad-hoc burst, `docker compose up --scale nuha-api-<code>=N`. cpu and the
        # memory reservation are uniform across dialects, so they stay shared env.
        # Each backend builds AND runs its own per-dialect image (only that
        # dialect's model is baked in). The image tag is ${NUHA_IMAGE_PREFIX}:<code>
        # (default prefix nuha-api), so `docker compose build` yields nuha-api:arz,
        # nuha-api:acm, ... and `docker compose up` runs them. The build passes
        # --build-arg DIALECT=<code>, which the Dockerfile uses to download only
        # that model; the runtime DIALECT env (below) must match the baked model.
        # image/build/DIALECT are per-dialect, so they are rendered here rather
        # than shared via the x-backend anchor.
        backends.append(
            f"  nuha-api-{code}:\n"
            f"    <<: *backend\n"
            f"    image: ${{NUHA_IMAGE_PREFIX:-nuha-api}}:{code}\n"
            f"    build:\n"
            f"      context: .\n"
            f"      dockerfile: Dockerfile\n"
            f"      args:\n"
            f"        - DIALECT={code}\n"
            f"    environment:\n"
            f"      - DIALECT={code}\n"
            f"    deploy:\n"
            f"      replicas: {replicas}\n"
            f"      resources:\n"
            f"        limits:\n"
            f'          cpus: "${{BACKEND_CPU_LIMIT:-2.0}}"\n'
            f"          memory: {mem}\n"
            f"        reservations:\n"
            f"          memory: ${{BACKEND_MEM_RESERVATION:-512m}}"
        )

    text = COMPOSE_TEMPLATE.read_text(encoding="utf-8")
    # Drop the template's own leading comment block (everything before `name:`).
    text = text[text.index("name:") :]
    text = text.replace(DEPENDS_MARKER, depends_on)
    text = text.replace(BACKENDS_MARKER, "\n\n".join(backends))
    return GENERATED_HEADER + text


def render_nginx(dialects: dict[str, dict]) -> str:
    codes = list(dialects)
    human_list = ", ".join(codes)

    lines = [
        "# GENERATED by scripts/render_config.py. Do not edit.",
        "# Rendered to /etc/nginx/conf.d/dialects.conf at container start; nginx",
        "# envsubst fills the default-dialect placeholder below (NGINX_ENVSUBST_FILTER",
        "# limits substitution to that one variable, leaving nginx $vars intact).",
        "# Maps ?dialect= to the matching backend; unknown -> empty -> 400.",
        "map $arg_dialect $dialect_backend {",
        '    ""      nuha-api-${DEFAULT_DIALECT}:8000;',
    ]
    for code in codes:
        lines.append(f"    {code:<7} nuha-api-{code}:8000;")
    lines += [
        '    default "";',
        "}",
        "# Docs are dialect-independent, served from the default dialect's backend.",
        "map $host $docs_backend { default nuha-api-${DEFAULT_DIALECT}:8000; }",
        f'map $host $invalid_dialect_msg {{ default "Invalid dialect. '
        f'Must be one of: {human_list}."; }}',
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    dialects = load_dialects()

    COMPOSE_OUTPUT.write_text(render_compose(dialects), encoding="utf-8")
    NGINX_OUTPUT.parent.mkdir(exist_ok=True)
    NGINX_OUTPUT.write_text(render_nginx(dialects), encoding="utf-8")

    codes = ", ".join(dialects)
    print(
        f"wrote {COMPOSE_OUTPUT.relative_to(ROOT)} and "
        f"{NGINX_OUTPUT.relative_to(ROOT)} for dialects: {codes}"
    )


if __name__ == "__main__":
    main()
