"""Generate deployment config from the dialect files, the single source of truth.

Compose can't loop and nginx can't read JSON, so both derive their per-dialect
parts from app/dialects/<code>.json at COMMIT time (via the render-config
pre-commit hook), keeping the two in lockstep so they cannot drift. This script
writes two committed, reviewable artifacts:

  - compose.yml ............ one backend service per dialect, each with its own
                             mem_limit and baseline replicas from that dialect's
                             file, plus the proxy depends_on. Rendered from
                             compose.template.yml.
  - nginx/dialects.conf.template  routing map (?dialect= -> backend), docs
                             backend, and the invalid-dialect message. The proxy
                             renders it to /etc/nginx/conf.d/dialects.conf at
                             startup via nginx's built-in envsubst, filling
                             ${DEFAULT_DIALECT} (a runtime env) for the
                             no-dialect fallback and docs routing.
  - .woodpecker/build-{latest,stable}-image.yaml  the per-dialect build steps and
                             the notify depends_on lists, rendered from the
                             hand-edited woodpecker-templates/{latest,stable}.yaml
                             (same template -> generated pattern as compose) so CI
                             builds every dialect's image with no hand edit. The
                             generated files carry a do-not-edit header; edit the
                             templates, where the check-lockfile gate and
                             everything else live.

Adding a dialect = drop app/dialects/<code>.json and commit; the hook
regenerates all of these. The dialect code is the filename stem; the backend
service is nuha-api-<code>:8000.

Run from the repo root:  python scripts/render_config.py
"""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DIALECTS_DIR = ROOT / "app" / "dialects"

COMPOSE_TEMPLATE = ROOT / "compose.template.yml"
COMPOSE_OUTPUT = ROOT / "compose.yml"
NGINX_OUTPUT = ROOT / "nginx" / "dialects.conf.template"

DEPENDS_MARKER = "# __PROXY_DEPENDS_ON__  (generated)"
BACKENDS_MARKER = "# __BACKENDS__  (generated: one service per dialect)"

DEFAULT_MEM_LIMIT = "4g"
DEFAULT_REPLICAS = 1

GENERATED_HEADER = (
    "# GENERATED by scripts/render_config.py. Do not edit.\n"
    "# Edit compose.template.yml or add/remove app/dialects/<code>.json,\n"
    "# then re-run: python scripts/render_config.py\n"
)


def load_dialects() -> dict[str, dict]:
    """Return {code: config} for every app/dialects/<code>.json, sorted by code."""
    dialects = {
        p.stem: json.loads(p.read_text(encoding="utf-8"))
        for p in sorted(DIALECTS_DIR.glob("*.json"))
    }
    if not dialects:
        raise SystemExit(f"No dialect files found in {DIALECTS_DIR}")
    return dialects


def render_compose(dialects: dict[str, dict]) -> str:
    codes = list(dialects)

    depends_on = "\n".join(
        f"      nuha-api-{code}:\n        condition: service_healthy" for code in codes
    )

    backends = []
    for code, cfg in dialects.items():
        # Per-dialect knobs come from the dialect file (the single source of truth
        # for anything dialect-specific): mem_limit and the baseline replica count.
        mem = cfg.get("mem_limit", DEFAULT_MEM_LIMIT)
        replicas = cfg.get("replicas", DEFAULT_REPLICAS)
        # No container_name: a service with replicas needs unique container names,
        # so Compose names them nuha-api-<code>-1, -2, ... The service name
        # nuha-api-<code> still resolves (via Docker DNS) to every replica, which
        # is what the proxy's variable proxy_pass and the depends_on use. To change
        # the baseline, edit "replicas" in the dialect file and re-render; for an
        # ad-hoc burst, `docker compose up --scale nuha-api-<code>=N`. cpu and the
        # memory reservation are uniform across dialects, so they stay shared env.
        # Each backend builds AND runs its own per-dialect image (only that
        # dialect's model is baked in). The image tag is ${NUHA_IMAGE_PREFIX}:<code>
        # (default prefix nuha-api), so `docker compose build` yields nuha-api:arz,
        # nuha-api:acm, ... and `docker compose up` runs them. The build passes
        # --build-arg DIALECT=<code>, which the Dockerfile uses to download only
        # that model; the runtime DIALECT env (below) must match the baked model.
        # image/build/DIALECT are per-dialect, so they are rendered here rather
        # than shared via the x-backend anchor.
        backends.append(
            f"  nuha-api-{code}:\n"
            f"    <<: *backend\n"
            f"    image: ${{NUHA_IMAGE_PREFIX:-nuha-api}}:{code}\n"
            f"    build:\n"
            f"      context: .\n"
            f"      dockerfile: Dockerfile\n"
            f"      args:\n"
            f"        - DIALECT={code}\n"
            f"    environment:\n"
            f"      - DIALECT={code}\n"
            f"    deploy:\n"
            f"      replicas: {replicas}\n"
            f"      resources:\n"
            f"        limits:\n"
            f'          cpus: "${{BACKEND_CPU_LIMIT:-2.0}}"\n'
            f"          memory: {mem}\n"
            f"        reservations:\n"
            f"          memory: ${{BACKEND_MEM_RESERVATION:-512m}}"
        )

    text = COMPOSE_TEMPLATE.read_text(encoding="utf-8")
    # Drop the template's own leading comment block (everything before `name:`).
    text = text[text.index("name:") :]
    text = text.replace(DEPENDS_MARKER, depends_on)
    text = text.replace(BACKENDS_MARKER, "\n\n".join(backends))
    return GENERATED_HEADER + text


def render_nginx(dialects: dict[str, dict]) -> str:
    codes = list(dialects)
    human_list = ", ".join(codes)

    lines = [
        "# GENERATED by scripts/render_config.py. Do not edit.",
        "# Edit app/dialects/<code>.json and re-render, not this file.",
        "# Rendered to /etc/nginx/conf.d/dialects.conf at container start; nginx",
        "# envsubst fills the default-dialect placeholder below (NGINX_ENVSUBST_FILTER",
        "# limits substitution to that one variable, leaving nginx $vars intact).",
        "# Maps ?dialect= to the matching backend; unknown -> empty -> 400.",
        "map $arg_dialect $dialect_backend {",
        '    ""      nuha-api-${DEFAULT_DIALECT}:8000;',
    ]
    for code in codes:
        lines.append(f"    {code:<7} nuha-api-{code}:8000;")
    lines += [
        '    default "";',
        "}",
        "# Docs are dialect-independent, served from the default dialect's backend.",
        "map $host $docs_backend { default nuha-api-${DEFAULT_DIALECT}:8000; }",
        f'map $host $invalid_dialect_msg {{ default "Invalid dialect. '
        f'Must be one of: {human_list}."; }}',
        "",
    ]
    return "\n".join(lines)


# --- Woodpecker CI -----------------------------------------------------------
# The two pipeline files build one image per dialect. Each is rendered from a
# hand-edited woodpecker-templates/<channel>.yaml (the same template -> generated
# pattern as compose.template.yml -> compose.yml): render_config fills the build
# steps and the notify depends_on lists, one entry per dialect, so adding a
# dialect needs no CI edit. The templates live in woodpecker-templates/, not in
# .woodpecker/, because any *.yaml under .woodpecker/ is parsed as a pipeline.
# Everything else (triggers, secrets, notify steps, the single check-lockfile
# gate) is hand-edited in the template.
WOODPECKER_FILES = {
    "latest": {
        "template": ROOT / "woodpecker-templates" / "latest.yaml",
        "output": ROOT / ".woodpecker" / "build-latest-image.yaml",
    },
    "stable": {
        "template": ROOT / "woodpecker-templates" / "stable.yaml",
        "output": ROOT / ".woodpecker" / "build-stable-image.yaml",
    },
}

# Marker tokens the templates carry on their own lines; render fills each with one
# entry per dialect. Matched by substring, not exact text, so the human-readable
# annotation after the token can be edited freely without breaking the render.
BUILD_STEPS_TOKEN = "__BUILD_STEPS__"
BUILD_DEPENDS_TOKEN = "__BUILD_DEPENDS__"


def _wp_build_step(channel: str, code: str) -> str:
    """One docker-buildx build step for a dialect on the latest or stable channel."""
    if channel == "latest":
        tags = (code, f"{code}-latest", f"{code}-latest-${{CI_COMMIT_SHA}}")
    else:
        tags = (f"{code}-stable", f"{code}-stable-${{CI_COMMIT_SHA}}")
    tag_lines = "\n".join(f"        - {t}" for t in tags)
    # build_args MUST be a map: given a list the plugin collapses it into a
    # single "*" arg, so the build args (DIALECT included) never get set.
    return (
        f"  - name: build-{channel}-image-{code}\n"
        f"    image: woodpeckerci/plugin-docker-buildx\n"
        f"    settings:\n"
        f"      repo: *docker_repo\n"
        f"      registry: *registry_url\n"
        f"      dockerfile: ./Dockerfile\n"
        f"      tags:\n"
        f"{tag_lines}\n"
        f"      username:\n"
        f"        from_secret: REGISTRY_USERNAME\n"
        f"      password:\n"
        f"        from_secret: REGISTRY_SECRET\n"
        f"      build_args:\n"
        f"        DIALECT: {code}\n"
        f"        CI_COMMIT_SHA: ${{CI_COMMIT_SHA}}\n"
        f"        CI_REPO_URL: ${{CI_REPO_URL}}\n"
        f"        CI_PIPELINE_CREATED: ${{CI_PIPELINE_CREATED}}\n"
        f"    depends_on:\n"
        f"      - run-pre-commit-hooks\n"
        f"      - check-lockfile"
    )


def _woodpecker_header(template_name: str) -> str:
    return (
        "# GENERATED by scripts/render_config.py. Do not edit.\n"
        f"# Edit {template_name} or add/remove app/dialects/<code>.json,\n"
        "# then re-run: python scripts/render_config.py\n"
    )


def _strip_leading_comment(text: str) -> str:
    """Drop the template's leading comment block (the opening run of blank and #
    lines) so the generated file starts at the first real key. Robust to whatever
    the comment says, unlike keying on a sentinel word in it."""
    lines = text.split("\n")
    i = 0
    while i < len(lines) and (not lines[i].strip() or lines[i].lstrip().startswith("#")):
        i += 1
    return "\n".join(lines[i:])


def _fill_marker(text: str, token: str, block: str, where: str) -> str:
    """Replace every line containing `token` with `block`. Raises if the token is
    absent, so a template that lost its marker fails the render (and the pre-commit
    hook) loudly instead of silently dropping a generated section."""
    lines = text.split("\n")
    if not any(token in ln for ln in lines):
        raise SystemExit(f"render_config: marker {token} not found in {where}")
    return "\n".join(block if token in ln else ln for ln in lines)


def render_woodpecker(dialects: dict[str, dict]) -> None:
    """Render each .woodpecker pipeline from its hand-edited template.

    Fills the build-steps and notify-depends markers with one entry per dialect,
    drops the template's own leading comment, and stamps a do-not-edit header on
    the generated file (mirrors render_compose)."""
    codes = list(dialects)
    for channel, paths in WOODPECKER_FILES.items():
        steps = "\n\n".join(_wp_build_step(channel, c) for c in codes)
        depends = "\n".join(f"      - build-{channel}-image-{c}" for c in codes)
        ref = paths["template"].relative_to(ROOT).as_posix()
        text = _strip_leading_comment(paths["template"].read_text(encoding="utf-8"))
        text = _fill_marker(text, BUILD_STEPS_TOKEN, steps, ref)
        text = _fill_marker(text, BUILD_DEPENDS_TOKEN, depends, ref)
        paths["output"].write_text(_woodpecker_header(ref) + text, encoding="utf-8")


def main() -> None:
    dialects = load_dialects()

    COMPOSE_OUTPUT.write_text(render_compose(dialects), encoding="utf-8")
    NGINX_OUTPUT.parent.mkdir(exist_ok=True)
    NGINX_OUTPUT.write_text(render_nginx(dialects), encoding="utf-8")
    render_woodpecker(dialects)

    codes = ", ".join(dialects)
    print(
        f"wrote compose.yml, nginx/dialects.conf.template, and the .woodpecker "
        f"build steps for dialects: {codes}"
    )


if __name__ == "__main__":
    main()
